<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class AustralianPostParametersDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'australianPostShortBarHeight',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Aspose\Barcode\Bridge\UnitDTO',
        ),
        2 => array(
            'var' => 'australianPostEncodingTable',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var \Aspose\Barcode\Bridge\UnitDTO
     */
    public $australianPostShortBarHeight = null;
    /**
     * @var int
     */
    public $australianPostEncodingTable = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['australianPostShortBarHeight'])) {
                $this->australianPostShortBarHeight = $vals['australianPostShortBarHeight'];
            }
            if (isset($vals['australianPostEncodingTable'])) {
                $this->australianPostEncodingTable = $vals['australianPostEncodingTable'];
            }
        }
    }

    public function getName()
    {
        return 'AustralianPostParametersDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->australianPostShortBarHeight = new \Aspose\Barcode\Bridge\UnitDTO();
                        $xfer += $this->australianPostShortBarHeight->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->australianPostEncodingTable);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('AustralianPostParametersDTO');
        if ($this->australianPostShortBarHeight !== null) {
            if (!is_object($this->australianPostShortBarHeight)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('australianPostShortBarHeight', TType::STRUCT, 1);
            $xfer += $this->australianPostShortBarHeight->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->australianPostEncodingTable !== null) {
            $xfer += $output->writeFieldBegin('australianPostEncodingTable', TType::I32, 2);
            $xfer += $output->writeI32($this->australianPostEncodingTable);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
