<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class ExceptionKindDTO
{
    const INFO = 1;

    const WARN = 2;

    const APP_ERROR = 3;

    const SYS_ERROR = 4;

    static public $__names = array(
        1 => 'INFO',
        2 => 'WARN',
        3 => 'APP_ERROR',
        4 => 'SYS_ERROR',
    );
}

