<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ITFParametersDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'itfBorderThickness',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Aspose\Barcode\Bridge\UnitDTO',
        ),
        2 => array(
            'var' => 'itfBorderType',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'quietZoneCoef',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var \Aspose\Barcode\Bridge\UnitDTO
     */
    public $itfBorderThickness = null;
    /**
     * @var int
     */
    public $itfBorderType = null;
    /**
     * @var int
     */
    public $quietZoneCoef = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['itfBorderThickness'])) {
                $this->itfBorderThickness = $vals['itfBorderThickness'];
            }
            if (isset($vals['itfBorderType'])) {
                $this->itfBorderType = $vals['itfBorderType'];
            }
            if (isset($vals['quietZoneCoef'])) {
                $this->quietZoneCoef = $vals['quietZoneCoef'];
            }
        }
    }

    public function getName()
    {
        return 'ITFParametersDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->itfBorderThickness = new \Aspose\Barcode\Bridge\UnitDTO();
                        $xfer += $this->itfBorderThickness->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->itfBorderType);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->quietZoneCoef);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ITFParametersDTO');
        if ($this->itfBorderThickness !== null) {
            if (!is_object($this->itfBorderThickness)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('itfBorderThickness', TType::STRUCT, 1);
            $xfer += $this->itfBorderThickness->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->itfBorderType !== null) {
            $xfer += $output->writeFieldBegin('itfBorderType', TType::I32, 2);
            $xfer += $output->writeI32($this->itfBorderType);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->quietZoneCoef !== null) {
            $xfer += $output->writeFieldBegin('quietZoneCoef', TType::I32, 3);
            $xfer += $output->writeI32($this->quietZoneCoef);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
