<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ThriftAsposeBarcodeService_SwissQRBill_createAndSetCreditorReference_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'swissQRBillDTO',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Aspose\Barcode\Bridge\SwissQRBillDTO',
        ),
        2 => array(
            'var' => 'rawReference',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var \Aspose\Barcode\Bridge\SwissQRBillDTO
     */
    public $swissQRBillDTO = null;
    /**
     * @var string
     */
    public $rawReference = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['swissQRBillDTO'])) {
                $this->swissQRBillDTO = $vals['swissQRBillDTO'];
            }
            if (isset($vals['rawReference'])) {
                $this->rawReference = $vals['rawReference'];
            }
        }
    }

    public function getName()
    {
        return 'ThriftAsposeBarcodeService_SwissQRBill_createAndSetCreditorReference_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->swissQRBillDTO = new \Aspose\Barcode\Bridge\SwissQRBillDTO();
                        $xfer += $this->swissQRBillDTO->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->rawReference);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ThriftAsposeBarcodeService_SwissQRBill_createAndSetCreditorReference_args');
        if ($this->swissQRBillDTO !== null) {
            if (!is_object($this->swissQRBillDTO)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('swissQRBillDTO', TType::STRUCT, 1);
            $xfer += $this->swissQRBillDTO->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->rawReference !== null) {
            $xfer += $output->writeFieldBegin('rawReference', TType::STRING, 2);
            $xfer += $output->writeString($this->rawReference);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
