<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ThriftAsposeBarcodeService_ExtCodetextBuilder_getExtendedCodetext_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'codeTextBuilderType',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'extCodeItems',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Aspose\Barcode\Bridge\ExtCodeItemDTO',
                ),
        ),
    );

    /**
     * @var int
     */
    public $codeTextBuilderType = null;
    /**
     * @var \Aspose\Barcode\Bridge\ExtCodeItemDTO[]
     */
    public $extCodeItems = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['codeTextBuilderType'])) {
                $this->codeTextBuilderType = $vals['codeTextBuilderType'];
            }
            if (isset($vals['extCodeItems'])) {
                $this->extCodeItems = $vals['extCodeItems'];
            }
        }
    }

    public function getName()
    {
        return 'ThriftAsposeBarcodeService_ExtCodetextBuilder_getExtendedCodetext_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->codeTextBuilderType);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::LST) {
                        $this->extCodeItems = array();
                        $_size7 = 0;
                        $_etype10 = 0;
                        $xfer += $input->readListBegin($_etype10, $_size7);
                        for ($_i11 = 0; $_i11 < $_size7; ++$_i11) {
                            $elem12 = null;
                            $elem12 = new \Aspose\Barcode\Bridge\ExtCodeItemDTO();
                            $xfer += $elem12->read($input);
                            $this->extCodeItems []= $elem12;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ThriftAsposeBarcodeService_ExtCodetextBuilder_getExtendedCodetext_args');
        if ($this->codeTextBuilderType !== null) {
            $xfer += $output->writeFieldBegin('codeTextBuilderType', TType::I32, 1);
            $xfer += $output->writeI32($this->codeTextBuilderType);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->extCodeItems !== null) {
            if (!is_array($this->extCodeItems)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('extCodeItems', TType::LST, 2);
            $output->writeListBegin(TType::STRUCT, count($this->extCodeItems));
            foreach ($this->extCodeItems as $iter13) {
                $xfer += $iter13->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
