<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class CaptionParametersDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'text',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'font',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Aspose\Barcode\Bridge\FontUnitDTO',
        ),
        3 => array(
            'var' => 'visible',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        4 => array(
            'var' => 'textColor',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        5 => array(
            'var' => 'padding',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Aspose\Barcode\Bridge\PaddingDTO',
        ),
        6 => array(
            'var' => 'alignment',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        7 => array(
            'var' => 'noWrap',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
    );

    /**
     * @var string
     */
    public $text = null;
    /**
     * @var \Aspose\Barcode\Bridge\FontUnitDTO
     */
    public $font = null;
    /**
     * @var bool
     */
    public $visible = null;
    /**
     * @var int
     */
    public $textColor = null;
    /**
     * @var \Aspose\Barcode\Bridge\PaddingDTO
     */
    public $padding = null;
    /**
     * @var int
     */
    public $alignment = null;
    /**
     * @var bool
     */
    public $noWrap = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['text'])) {
                $this->text = $vals['text'];
            }
            if (isset($vals['font'])) {
                $this->font = $vals['font'];
            }
            if (isset($vals['visible'])) {
                $this->visible = $vals['visible'];
            }
            if (isset($vals['textColor'])) {
                $this->textColor = $vals['textColor'];
            }
            if (isset($vals['padding'])) {
                $this->padding = $vals['padding'];
            }
            if (isset($vals['alignment'])) {
                $this->alignment = $vals['alignment'];
            }
            if (isset($vals['noWrap'])) {
                $this->noWrap = $vals['noWrap'];
            }
        }
    }

    public function getName()
    {
        return 'CaptionParametersDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->text);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->font = new \Aspose\Barcode\Bridge\FontUnitDTO();
                        $xfer += $this->font->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->visible);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->textColor);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRUCT) {
                        $this->padding = new \Aspose\Barcode\Bridge\PaddingDTO();
                        $xfer += $this->padding->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->alignment);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->noWrap);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('CaptionParametersDTO');
        if ($this->text !== null) {
            $xfer += $output->writeFieldBegin('text', TType::STRING, 1);
            $xfer += $output->writeString($this->text);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->font !== null) {
            if (!is_object($this->font)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('font', TType::STRUCT, 2);
            $xfer += $this->font->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->visible !== null) {
            $xfer += $output->writeFieldBegin('visible', TType::BOOL, 3);
            $xfer += $output->writeBool($this->visible);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->textColor !== null) {
            $xfer += $output->writeFieldBegin('textColor', TType::I32, 4);
            $xfer += $output->writeI32($this->textColor);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->padding !== null) {
            if (!is_object($this->padding)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('padding', TType::STRUCT, 5);
            $xfer += $this->padding->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->alignment !== null) {
            $xfer += $output->writeFieldBegin('alignment', TType::I32, 6);
            $xfer += $output->writeI32($this->alignment);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->noWrap !== null) {
            $xfer += $output->writeFieldBegin('noWrap', TType::BOOL, 7);
            $xfer += $output->writeBool($this->noWrap);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
