<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Code128DataPortionDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'data',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'code128SubType',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var string
     */
    public $data = null;
    /**
     * @var int
     */
    public $code128SubType = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['data'])) {
                $this->data = $vals['data'];
            }
            if (isset($vals['code128SubType'])) {
                $this->code128SubType = $vals['code128SubType'];
            }
        }
    }

    public function getName()
    {
        return 'Code128DataPortionDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->data);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->code128SubType);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('Code128DataPortionDTO');
        if ($this->data !== null) {
            $xfer += $output->writeFieldBegin('data', TType::STRING, 1);
            $xfer += $output->writeString($this->data);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->code128SubType !== null) {
            $xfer += $output->writeFieldBegin('code128SubType', TType::I32, 2);
            $xfer += $output->writeI32($this->code128SubType);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
