<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class DotCodeParametersDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'aspectRatio',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
        2 => array(
            'var' => 'dotCodeEncodeMode',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'isReaderInitialization',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        4 => array(
            'var' => 'dotCodeStructuredAppendModeBarcodeId',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        5 => array(
            'var' => 'dotCodeStructuredAppendModeBarcodesCount',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        6 => array(
            'var' => 'eCIEncoding',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        7 => array(
            'var' => 'rows',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        8 => array(
            'var' => 'columns',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var double
     */
    public $aspectRatio = null;
    /**
     * @var int
     */
    public $dotCodeEncodeMode = null;
    /**
     * @var bool
     */
    public $isReaderInitialization = null;
    /**
     * @var int
     */
    public $dotCodeStructuredAppendModeBarcodeId = null;
    /**
     * @var int
     */
    public $dotCodeStructuredAppendModeBarcodesCount = null;
    /**
     * @var int
     */
    public $eCIEncoding = null;
    /**
     * @var int
     */
    public $rows = null;
    /**
     * @var int
     */
    public $columns = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['aspectRatio'])) {
                $this->aspectRatio = $vals['aspectRatio'];
            }
            if (isset($vals['dotCodeEncodeMode'])) {
                $this->dotCodeEncodeMode = $vals['dotCodeEncodeMode'];
            }
            if (isset($vals['isReaderInitialization'])) {
                $this->isReaderInitialization = $vals['isReaderInitialization'];
            }
            if (isset($vals['dotCodeStructuredAppendModeBarcodeId'])) {
                $this->dotCodeStructuredAppendModeBarcodeId = $vals['dotCodeStructuredAppendModeBarcodeId'];
            }
            if (isset($vals['dotCodeStructuredAppendModeBarcodesCount'])) {
                $this->dotCodeStructuredAppendModeBarcodesCount = $vals['dotCodeStructuredAppendModeBarcodesCount'];
            }
            if (isset($vals['eCIEncoding'])) {
                $this->eCIEncoding = $vals['eCIEncoding'];
            }
            if (isset($vals['rows'])) {
                $this->rows = $vals['rows'];
            }
            if (isset($vals['columns'])) {
                $this->columns = $vals['columns'];
            }
        }
    }

    public function getName()
    {
        return 'DotCodeParametersDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->aspectRatio);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->dotCodeEncodeMode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->isReaderInitialization);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->dotCodeStructuredAppendModeBarcodeId);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->dotCodeStructuredAppendModeBarcodesCount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->eCIEncoding);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->rows);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 8:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->columns);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('DotCodeParametersDTO');
        if ($this->aspectRatio !== null) {
            $xfer += $output->writeFieldBegin('aspectRatio', TType::DOUBLE, 1);
            $xfer += $output->writeDouble($this->aspectRatio);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dotCodeEncodeMode !== null) {
            $xfer += $output->writeFieldBegin('dotCodeEncodeMode', TType::I32, 2);
            $xfer += $output->writeI32($this->dotCodeEncodeMode);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->isReaderInitialization !== null) {
            $xfer += $output->writeFieldBegin('isReaderInitialization', TType::BOOL, 3);
            $xfer += $output->writeBool($this->isReaderInitialization);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dotCodeStructuredAppendModeBarcodeId !== null) {
            $xfer += $output->writeFieldBegin('dotCodeStructuredAppendModeBarcodeId', TType::I32, 4);
            $xfer += $output->writeI32($this->dotCodeStructuredAppendModeBarcodeId);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dotCodeStructuredAppendModeBarcodesCount !== null) {
            $xfer += $output->writeFieldBegin('dotCodeStructuredAppendModeBarcodesCount', TType::I32, 5);
            $xfer += $output->writeI32($this->dotCodeStructuredAppendModeBarcodesCount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->eCIEncoding !== null) {
            $xfer += $output->writeFieldBegin('eCIEncoding', TType::I32, 6);
            $xfer += $output->writeI32($this->eCIEncoding);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->rows !== null) {
            $xfer += $output->writeFieldBegin('rows', TType::I32, 7);
            $xfer += $output->writeI32($this->rows);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->columns !== null) {
            $xfer += $output->writeFieldBegin('columns', TType::I32, 8);
            $xfer += $output->writeI32($this->columns);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
