<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class DotCodeExtendedParametersDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'dotCodeStructuredAppendModeBarcodesCount',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'dotCodeStructuredAppendModeBarcodeId',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'dotCodeIsReaderInitialization',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        4 => array(
            'var' => 'toString',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var int
     */
    public $dotCodeStructuredAppendModeBarcodesCount = null;
    /**
     * @var int
     */
    public $dotCodeStructuredAppendModeBarcodeId = null;
    /**
     * @var bool
     */
    public $dotCodeIsReaderInitialization = null;
    /**
     * @var string
     */
    public $toString = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['dotCodeStructuredAppendModeBarcodesCount'])) {
                $this->dotCodeStructuredAppendModeBarcodesCount = $vals['dotCodeStructuredAppendModeBarcodesCount'];
            }
            if (isset($vals['dotCodeStructuredAppendModeBarcodeId'])) {
                $this->dotCodeStructuredAppendModeBarcodeId = $vals['dotCodeStructuredAppendModeBarcodeId'];
            }
            if (isset($vals['dotCodeIsReaderInitialization'])) {
                $this->dotCodeIsReaderInitialization = $vals['dotCodeIsReaderInitialization'];
            }
            if (isset($vals['toString'])) {
                $this->toString = $vals['toString'];
            }
        }
    }

    public function getName()
    {
        return 'DotCodeExtendedParametersDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->dotCodeStructuredAppendModeBarcodesCount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->dotCodeStructuredAppendModeBarcodeId);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->dotCodeIsReaderInitialization);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->toString);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('DotCodeExtendedParametersDTO');
        if ($this->dotCodeStructuredAppendModeBarcodesCount !== null) {
            $xfer += $output->writeFieldBegin('dotCodeStructuredAppendModeBarcodesCount', TType::I32, 1);
            $xfer += $output->writeI32($this->dotCodeStructuredAppendModeBarcodesCount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dotCodeStructuredAppendModeBarcodeId !== null) {
            $xfer += $output->writeFieldBegin('dotCodeStructuredAppendModeBarcodeId', TType::I32, 2);
            $xfer += $output->writeI32($this->dotCodeStructuredAppendModeBarcodeId);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->dotCodeIsReaderInitialization !== null) {
            $xfer += $output->writeFieldBegin('dotCodeIsReaderInitialization', TType::BOOL, 3);
            $xfer += $output->writeBool($this->dotCodeIsReaderInitialization);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->toString !== null) {
            $xfer += $output->writeFieldBegin('toString', TType::STRING, 4);
            $xfer += $output->writeString($this->toString);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
