<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class DotCodeExtendedParametersDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'structuredAppendModeBarcodesCount',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'structuredAppendModeBarcodeId',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'isReaderInitialization',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        4 => array(
            'var' => 'toString',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var int
     */
    public $structuredAppendModeBarcodesCount = null;
    /**
     * @var int
     */
    public $structuredAppendModeBarcodeId = null;
    /**
     * @var bool
     */
    public $isReaderInitialization = null;
    /**
     * @var string
     */
    public $toString = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['structuredAppendModeBarcodesCount'])) {
                $this->structuredAppendModeBarcodesCount = $vals['structuredAppendModeBarcodesCount'];
            }
            if (isset($vals['structuredAppendModeBarcodeId'])) {
                $this->structuredAppendModeBarcodeId = $vals['structuredAppendModeBarcodeId'];
            }
            if (isset($vals['isReaderInitialization'])) {
                $this->isReaderInitialization = $vals['isReaderInitialization'];
            }
            if (isset($vals['toString'])) {
                $this->toString = $vals['toString'];
            }
        }
    }

    public function getName()
    {
        return 'DotCodeExtendedParametersDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->structuredAppendModeBarcodesCount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->structuredAppendModeBarcodeId);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->isReaderInitialization);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->toString);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('DotCodeExtendedParametersDTO');
        if ($this->structuredAppendModeBarcodesCount !== null) {
            $xfer += $output->writeFieldBegin('structuredAppendModeBarcodesCount', TType::I32, 1);
            $xfer += $output->writeI32($this->structuredAppendModeBarcodesCount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->structuredAppendModeBarcodeId !== null) {
            $xfer += $output->writeFieldBegin('structuredAppendModeBarcodeId', TType::I32, 2);
            $xfer += $output->writeI32($this->structuredAppendModeBarcodeId);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->isReaderInitialization !== null) {
            $xfer += $output->writeFieldBegin('isReaderInitialization', TType::BOOL, 3);
            $xfer += $output->writeBool($this->isReaderInitialization);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->toString !== null) {
            $xfer += $output->writeFieldBegin('toString', TType::STRING, 4);
            $xfer += $output->writeString($this->toString);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
