<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class HanXinParametersDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'hanXinVersion',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'hanXinErrorLevel',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'hanXinEncodeMode',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        4 => array(
            'var' => 'hanXinECIEncoding',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var int
     */
    public $hanXinVersion = null;
    /**
     * @var int
     */
    public $hanXinErrorLevel = null;
    /**
     * @var int
     */
    public $hanXinEncodeMode = null;
    /**
     * @var int
     */
    public $hanXinECIEncoding = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['hanXinVersion'])) {
                $this->hanXinVersion = $vals['hanXinVersion'];
            }
            if (isset($vals['hanXinErrorLevel'])) {
                $this->hanXinErrorLevel = $vals['hanXinErrorLevel'];
            }
            if (isset($vals['hanXinEncodeMode'])) {
                $this->hanXinEncodeMode = $vals['hanXinEncodeMode'];
            }
            if (isset($vals['hanXinECIEncoding'])) {
                $this->hanXinECIEncoding = $vals['hanXinECIEncoding'];
            }
        }
    }

    public function getName()
    {
        return 'HanXinParametersDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->hanXinVersion);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->hanXinErrorLevel);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->hanXinEncodeMode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->hanXinECIEncoding);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('HanXinParametersDTO');
        if ($this->hanXinVersion !== null) {
            $xfer += $output->writeFieldBegin('hanXinVersion', TType::I32, 1);
            $xfer += $output->writeI32($this->hanXinVersion);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->hanXinErrorLevel !== null) {
            $xfer += $output->writeFieldBegin('hanXinErrorLevel', TType::I32, 2);
            $xfer += $output->writeI32($this->hanXinErrorLevel);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->hanXinEncodeMode !== null) {
            $xfer += $output->writeFieldBegin('hanXinEncodeMode', TType::I32, 3);
            $xfer += $output->writeI32($this->hanXinEncodeMode);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->hanXinECIEncoding !== null) {
            $xfer += $output->writeFieldBegin('hanXinECIEncoding', TType::I32, 4);
            $xfer += $output->writeI32($this->hanXinECIEncoding);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
