<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class MaxiCodeParametersDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'mode',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'encodeMode',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'eciEncoding',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        4 => array(
            'var' => 'structuredAppendModeBarcodeId',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        5 => array(
            'var' => 'structuredAppendModeBarcodesCount',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        6 => array(
            'var' => 'aspectRatio',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
    );

    /**
     * @var int
     */
    public $mode = null;
    /**
     * @var int
     */
    public $encodeMode = null;
    /**
     * @var int
     */
    public $eciEncoding = null;
    /**
     * @var int
     */
    public $structuredAppendModeBarcodeId = null;
    /**
     * @var int
     */
    public $structuredAppendModeBarcodesCount = null;
    /**
     * @var double
     */
    public $aspectRatio = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['mode'])) {
                $this->mode = $vals['mode'];
            }
            if (isset($vals['encodeMode'])) {
                $this->encodeMode = $vals['encodeMode'];
            }
            if (isset($vals['eciEncoding'])) {
                $this->eciEncoding = $vals['eciEncoding'];
            }
            if (isset($vals['structuredAppendModeBarcodeId'])) {
                $this->structuredAppendModeBarcodeId = $vals['structuredAppendModeBarcodeId'];
            }
            if (isset($vals['structuredAppendModeBarcodesCount'])) {
                $this->structuredAppendModeBarcodesCount = $vals['structuredAppendModeBarcodesCount'];
            }
            if (isset($vals['aspectRatio'])) {
                $this->aspectRatio = $vals['aspectRatio'];
            }
        }
    }

    public function getName()
    {
        return 'MaxiCodeParametersDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->mode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->encodeMode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->eciEncoding);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->structuredAppendModeBarcodeId);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->structuredAppendModeBarcodesCount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->aspectRatio);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('MaxiCodeParametersDTO');
        if ($this->mode !== null) {
            $xfer += $output->writeFieldBegin('mode', TType::I32, 1);
            $xfer += $output->writeI32($this->mode);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->encodeMode !== null) {
            $xfer += $output->writeFieldBegin('encodeMode', TType::I32, 2);
            $xfer += $output->writeI32($this->encodeMode);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->eciEncoding !== null) {
            $xfer += $output->writeFieldBegin('eciEncoding', TType::I32, 3);
            $xfer += $output->writeI32($this->eciEncoding);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->structuredAppendModeBarcodeId !== null) {
            $xfer += $output->writeFieldBegin('structuredAppendModeBarcodeId', TType::I32, 4);
            $xfer += $output->writeI32($this->structuredAppendModeBarcodeId);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->structuredAppendModeBarcodesCount !== null) {
            $xfer += $output->writeFieldBegin('structuredAppendModeBarcodesCount', TType::I32, 5);
            $xfer += $output->writeI32($this->structuredAppendModeBarcodesCount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->aspectRatio !== null) {
            $xfer += $output->writeFieldBegin('aspectRatio', TType::DOUBLE, 6);
            $xfer += $output->writeDouble($this->aspectRatio);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
