<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class QrStructuredAppendParametersDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'parityByte',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'sequenceIndicator',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'totalCount',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var int
     */
    public $parityByte = null;
    /**
     * @var int
     */
    public $sequenceIndicator = null;
    /**
     * @var int
     */
    public $totalCount = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['parityByte'])) {
                $this->parityByte = $vals['parityByte'];
            }
            if (isset($vals['sequenceIndicator'])) {
                $this->sequenceIndicator = $vals['sequenceIndicator'];
            }
            if (isset($vals['totalCount'])) {
                $this->totalCount = $vals['totalCount'];
            }
        }
    }

    public function getName()
    {
        return 'QrStructuredAppendParametersDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->parityByte);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->sequenceIndicator);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->totalCount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('QrStructuredAppendParametersDTO');
        if ($this->parityByte !== null) {
            $xfer += $output->writeFieldBegin('parityByte', TType::I32, 1);
            $xfer += $output->writeI32($this->parityByte);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->sequenceIndicator !== null) {
            $xfer += $output->writeFieldBegin('sequenceIndicator', TType::I32, 2);
            $xfer += $output->writeI32($this->sequenceIndicator);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->totalCount !== null) {
            $xfer += $output->writeFieldBegin('totalCount', TType::I32, 3);
            $xfer += $output->writeI32($this->totalCount);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
