<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class SvgParametersDTO
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'isExplicitSizeInPixels',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        2 => array(
            'var' => 'isTextDrawnInTextElement',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        3 => array(
            'var' => 'svgColorMode',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var bool
     */
    public $isExplicitSizeInPixels = null;
    /**
     * @var bool
     */
    public $isTextDrawnInTextElement = null;
    /**
     * @var int
     */
    public $svgColorMode = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['isExplicitSizeInPixels'])) {
                $this->isExplicitSizeInPixels = $vals['isExplicitSizeInPixels'];
            }
            if (isset($vals['isTextDrawnInTextElement'])) {
                $this->isTextDrawnInTextElement = $vals['isTextDrawnInTextElement'];
            }
            if (isset($vals['svgColorMode'])) {
                $this->svgColorMode = $vals['svgColorMode'];
            }
        }
    }

    public function getName()
    {
        return 'SvgParametersDTO';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->isExplicitSizeInPixels);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->isTextDrawnInTextElement);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->svgColorMode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('SvgParametersDTO');
        if ($this->isExplicitSizeInPixels !== null) {
            $xfer += $output->writeFieldBegin('isExplicitSizeInPixels', TType::BOOL, 1);
            $xfer += $output->writeBool($this->isExplicitSizeInPixels);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->isTextDrawnInTextElement !== null) {
            $xfer += $output->writeFieldBegin('isTextDrawnInTextElement', TType::BOOL, 2);
            $xfer += $output->writeBool($this->isTextDrawnInTextElement);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->svgColorMode !== null) {
            $xfer += $output->writeFieldBegin('svgColorMode', TType::I32, 3);
            $xfer += $output->writeI32($this->svgColorMode);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
