<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ThriftAsposeBarcodeService_Quadrangle_containsQuadrangle_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'thisQuadrangle',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Aspose\Barcode\Bridge\QuadrangleDTO',
        ),
        2 => array(
            'var' => 'anotherQuadrangle',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Aspose\Barcode\Bridge\QuadrangleDTO',
        ),
    );

    /**
     * @var \Aspose\Barcode\Bridge\QuadrangleDTO
     */
    public $thisQuadrangle = null;
    /**
     * @var \Aspose\Barcode\Bridge\QuadrangleDTO
     */
    public $anotherQuadrangle = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['thisQuadrangle'])) {
                $this->thisQuadrangle = $vals['thisQuadrangle'];
            }
            if (isset($vals['anotherQuadrangle'])) {
                $this->anotherQuadrangle = $vals['anotherQuadrangle'];
            }
        }
    }

    public function getName()
    {
        return 'ThriftAsposeBarcodeService_Quadrangle_containsQuadrangle_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->thisQuadrangle = new \Aspose\Barcode\Bridge\QuadrangleDTO();
                        $xfer += $this->thisQuadrangle->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->anotherQuadrangle = new \Aspose\Barcode\Bridge\QuadrangleDTO();
                        $xfer += $this->anotherQuadrangle->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ThriftAsposeBarcodeService_Quadrangle_containsQuadrangle_args');
        if ($this->thisQuadrangle !== null) {
            if (!is_object($this->thisQuadrangle)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('thisQuadrangle', TType::STRUCT, 1);
            $xfer += $this->thisQuadrangle->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->anotherQuadrangle !== null) {
            if (!is_object($this->anotherQuadrangle)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('anotherQuadrangle', TType::STRUCT, 2);
            $xfer += $this->anotherQuadrangle->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
