<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ThriftAsposeBarcodeService_BaseGenerationParameters_updateResolution_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'baseGenerationParameters',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Aspose\Barcode\Bridge\BaseGenerationParametersDTO',
        ),
        2 => array(
            'var' => 'resolution',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
    );

    /**
     * @var \Aspose\Barcode\Bridge\BaseGenerationParametersDTO
     */
    public $baseGenerationParameters = null;
    /**
     * @var double
     */
    public $resolution = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['baseGenerationParameters'])) {
                $this->baseGenerationParameters = $vals['baseGenerationParameters'];
            }
            if (isset($vals['resolution'])) {
                $this->resolution = $vals['resolution'];
            }
        }
    }

    public function getName()
    {
        return 'ThriftAsposeBarcodeService_BaseGenerationParameters_updateResolution_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->baseGenerationParameters = new \Aspose\Barcode\Bridge\BaseGenerationParametersDTO();
                        $xfer += $this->baseGenerationParameters->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->resolution);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ThriftAsposeBarcodeService_BaseGenerationParameters_updateResolution_args');
        if ($this->baseGenerationParameters !== null) {
            if (!is_object($this->baseGenerationParameters)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('baseGenerationParameters', TType::STRUCT, 1);
            $xfer += $this->baseGenerationParameters->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->resolution !== null) {
            $xfer += $output->writeFieldBegin('resolution', TType::DOUBLE, 2);
            $xfer += $output->writeDouble($this->resolution);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
