<?php
namespace Aspose\Barcode\Bridge;

/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ThriftAsposeBarcodeService_ComplexBarcodeGenerator_generateBarcodeImage_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'complexBarcodeGeneratorDTO',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Aspose\Barcode\Bridge\ComplexBarcodeGeneratorDTO',
        ),
        2 => array(
            'var' => 'imageFormat',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'base64LicenseContent',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var \Aspose\Barcode\Bridge\ComplexBarcodeGeneratorDTO
     */
    public $complexBarcodeGeneratorDTO = null;
    /**
     * @var int
     */
    public $imageFormat = null;
    /**
     * @var string
     */
    public $base64LicenseContent = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['complexBarcodeGeneratorDTO'])) {
                $this->complexBarcodeGeneratorDTO = $vals['complexBarcodeGeneratorDTO'];
            }
            if (isset($vals['imageFormat'])) {
                $this->imageFormat = $vals['imageFormat'];
            }
            if (isset($vals['base64LicenseContent'])) {
                $this->base64LicenseContent = $vals['base64LicenseContent'];
            }
        }
    }

    public function getName()
    {
        return 'ThriftAsposeBarcodeService_ComplexBarcodeGenerator_generateBarcodeImage_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->complexBarcodeGeneratorDTO = new \Aspose\Barcode\Bridge\ComplexBarcodeGeneratorDTO();
                        $xfer += $this->complexBarcodeGeneratorDTO->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->imageFormat);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->base64LicenseContent);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ThriftAsposeBarcodeService_ComplexBarcodeGenerator_generateBarcodeImage_args');
        if ($this->complexBarcodeGeneratorDTO !== null) {
            if (!is_object($this->complexBarcodeGeneratorDTO)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('complexBarcodeGeneratorDTO', TType::STRUCT, 1);
            $xfer += $this->complexBarcodeGeneratorDTO->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->imageFormat !== null) {
            $xfer += $output->writeFieldBegin('imageFormat', TType::I32, 2);
            $xfer += $output->writeI32($this->imageFormat);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->base64LicenseContent !== null) {
            $xfer += $output->writeFieldBegin('base64LicenseContent', TType::STRING, 3);
            $xfer += $output->writeString($this->base64LicenseContent);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
